# Base image for Node.js (you can specify the version)
FROM node:18-alpine

# Set working directory for Docker
WORKDIR /var/www/nextjs/ExoticaLingerie

# Copy package.json files for both the front-end and back-end
COPY ./exotica/package.json ./exotica/
COPY ./exotica_backend/package.json ./exotica_backend/

# Install dependencies for both applications
RUN cd exotica && npm install
RUN cd exotica_backend && npm install

# Copy the source code for both applications
COPY ./exotica ./exotica/
COPY ./exotica_backend ./exotica_backend/

# Build Next.js front-end
RUN cd exotica && npm run build

# Expose the necessary ports (Next.js frontend on 3000, backend on 5000)
EXPOSE 3000 5016

# This Dockerfile does not need to include PM2 as it will be managed by the VPS
CMD ["echo", "Build complete, ready for deployment"]
