name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          cd /var/www/nextjs/ExoticaLingerie
          git pull origin master
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
