name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./exotica
        push: true
        tags: jayeshberani/exotica_frontend:latest

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: ./exotica_backend
        push: true
        tags: jayeshberani/exotica_backend:latest
